import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Tabbar from "./Components/tabbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
             @import url('https://fonts.googleapis.com/css2?family=Pacifico&display=swap');
        </style>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}  
      >
        <div className="relative ">
           {/* Page content */}
        <main className=""> 
          {children}
        </main>

        {/* Dock fixed at bottom */}
        <div className="absolute bottom-0 left-1/2 -translate-x-1/2">
          <Tabbar />
        </div>
        </div>

      {/* {children} */}
      {/* <Tabbar/>      */}
      </body>
    </html>
  );
}
