import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
             @import url('https://fonts.googleapis.com/css2?family=Pacifico&display=swap');
        </style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}   
      >
        {children}
        <div className="w-full h-full flex justify-center items-center">
        <footer className="w-[60%] h-[20%] rounded-xl shadow-sm shadow-zink-300 flex justify-center gap-4 items-center mt-[-3%]">
        <Link href={'/'} className="rounded-full">
        
        </Link>
        <Link href={'/about'}>About</Link>
        <Link href={'/contact'}>Contact</Link>
        <Link href={'https://github.com/RadhikaSuryawanshi'}>GitHub</Link>
        <Link href={'/Themes'}>Themes</Link>

        </footer> 
        </div>
      </body>
    </html>
  );
}
