import type { Metadata } from "next";
import { Geist, Geist_Mono, Boldonse } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/Component/QueryProvider";
// import ProductHook from "@/lib/Product/Product-hook";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const boldonse = Boldonse({
  variable: "--font-boldonse",
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <style>
@import url('https://fonts.googleapis.com/css2?family=Boldonse&display=swap');
</style>
</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${boldonse.variable} antialiased`}
      >
        <QueryProvider>
     
      {children}
      
      </QueryProvider>
      </body>
    </html>
  );
}
